name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Build Apps, Linter & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: 142.132.150.169
          username: user@yayasanyatimnurulanwar.biz.id
          password: W=Ku[V;9FgSt
