name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Run Dependencies & Linter
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Build Apps
        run: composer install

      - name: Generate Storage
        run: php artisan storage:link

      - name: Generate Environment
        run: cp .env.example .env.testing

      - name: Generate Application Key
        run: |
          php artisan key:generate --env=testing
          sed -i 's/APP_ENV=local/APP_ENV=${{ secrets.APP_ENV }}/' .env.testing
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }} /' .env.testing
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }} /' .env.testing
          sed -i 's/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }} /' .env.testing
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }} /' .env.testing

      - name: Launch Linter
        run: ./vendor/bin/pint

      - name: Launch Unit Test
        run: ./vendor/bin/phpunit --testsuite Feature
