name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Run Dependencies & Linter
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: MySQL Deploy Action
        uses: calxus/mysql-deploy-action@v1
        with:
          DATABASE_HOST: "127.0.0.1"
          DATABASE_PORT: "3306"
          DATABASE_NAME: "convert"
          DATABASE_USERNAME: "root"
          DATABASE_PASSWORD: ""
          DATABASE_SCRIPT: "/home/laptop/Documents/convert.sql"

      # - name: Install Dependencies
      #   run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      # - name: Launch Linter
      #   run: ./vendor/bin/pint
