name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Build Apps, Linter & Testing
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Build Apps
        run: composer install

      - name: Generate Storage Testing
        run: php artisan storage:link

      - name: Generate Environment Testing
        run: cp .env.example .env.testing

      - name: Generate App Key
        run: php artisan key:generate --env=testing

      - name: Generate Application Key Testing
        run: |
          sed -i 's#APP_ENV=local#APP_ENV=testing#' .env.testing
          sed -i "s#DB_HOST=127.0.0.1#DB_HOST=${{ secrets.DB_HOST_CICD_CONVERT }} #" .env.testing
          sed -i "s#DB_DATABASE=laravel#DB_DATABASE=${{ secrets.DB_DATABASE_CICD_CONVERT }} #" .env.testing
          sed -i "s#DB_USERNAME=root#DB_USERNAME=${{ secrets.DB_USERNAME_CICD_CONVERT }} #" .env.testing
          sed -i "s#DB_PASSWORD=#DB_PASSWORD=${{ secrets.DB_PASSWORD_CICD_CONVERT }} #" .env.testing

      - name: Generate Env Testing Logging
        run: |
          cat << 'EOF' >> .env.testing
          SALT_LOGGING='${{ secrets.SALT_LOGGING_TESTING }}'
          USER_MONITORING='${{ secrets.USER_MONITORING_TESTING }}'
          JWT_SECRET_MONITORING='${{ secrets.JWT_SECRET_MONITORING_TESTING }}'
          EOF

      - name: View .env.testing
        run: cat .env.testing

      - name: Update PHPUnit Configuration
        run: |
          sed -i "s#<env name=\"DB_DATABASE\" value=\"convert_testing\"/>#<env name=\"DB_DATABASE\" value=\"${{ secrets.DB_DATABASE_CICD_CONVERT }}\"/>#" phpunit.xml

      - name: Linter
        run: |
          linter_output=$(./vendor/bin/pint)
          if [[ $linter_output == *"FIXED"* ]]; then
            echo "there is an error in your code format, correct it and push the code again!"
            exit 1
          fi

      - name: Unit Test
        run: ./vendor/bin/phpunit --testsuite Feature

  ContinuousDeployment:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: ContinuousIntegration
    # if: github.ref == 'refs/heads/master'
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      # - name: Build Apps
      #   run: composer install

      # - name: Generate Environment Production
      #   run: cp .env.example .env

      # - name: Generate Application Key
      #   run: |
      #     sed -i 's|APP_NAME=Laravel|APP_NAME=${{ secrets.APP_NAME_CONVERT_PRODUCTION }}|' .env
      #     sed -i 's|APP_ENV=local|APP_ENV=production|' .env
      #     sed -i 's|APP_KEY=|APP_KEY=${{ secrets.APP_KEY_CONVERT_PRODUCTION }}|' .env
      #     sed -i 's|APP_DEBUG=true|APP_DEBUG=false|' .env
      #     sed -i 's|APP_URL=http://localhost|APP_URL=${{ secrets.APP_URL_CONVERT_PRODUCTION }}|' .env

      #     sed -i 's|DB_HOST=127.0.0.1|DB_HOST=${{ secrets.DB_HOST_CONVERT_PRODUCTION }} |' .env
      #     sed -i 's|DB_DATABASE=laravel|DB_DATABASE=${{ secrets.DB_DATABASE_CONVERT_PRODUCTION }} |' .env
      #     sed -i 's|DB_USERNAME=root|DB_USERNAME=${{ secrets.DB_USERNAME_CONVERT_PRODUCTION }} |' .env
      #     sed -i "s|DB_PASSWORD=|DB_PASSWORD=\"${{ secrets.DB_PASSWORD_CONVERT_PRODUCTION }}\"|" .env

      # - name: Generate Env Logging
      #   run: |
      #     cat << 'EOF' >> .env
      #     LOGGING_RESULT='${{ secrets.LOGGING_RESULT_CONVERT_PRODUCTION }}'
      #     LOGGING_SALT='${{ secrets.LOGGING_SALT_CONVERT_PRODUCTION }}'
      #     EOF

      # - name: FTP-Deploy-Data
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
      #   with:
      #     server: ${{ secrets.FTP_HOST_CONVERT }}
      #     username: ${{ secrets.FTP_USERNAME_CONVERT_DATA }}
      #     password: ${{ secrets.FTP_PASSWORD_CONVERT_DATA }}
      #     exclude: |
      #       public/**
      #       .env.testing
      #       phpunit.xml

      # - name: Change App Data Location
      #   run: |
      #     sed -i 's|/../storage/framework/maintenance.php|/../convert_file/storage/framework/maintenance.php|g' public/index.php
      #     sed -i 's|/../vendor/autoload.php|/../convert_file/vendor/autoload.php|g' public/index.php
      #     sed -i 's|/../bootstrap/app.php|/../convert_file/bootstrap/app.php|g' public/index.php
      #     rm -rf public/storage

      # - name: FTP-Deploy-Public
      #   uses: webitsbr/github-to-ftp@1.0.1
      #   with:
      #     server: ${{ secrets.FTP_HOST_CONVERT }}
      #     username: ${{ secrets.FTP_USERNAME_CONVERT_PUBLIC }}
      #     password: ${{ secrets.FTP_PASSWORD_CONVERT_PUBLIC }}
      #     local-dir: "./public/"
