on:
  push:
    branches:
      - feature_03_jpg_to_pdf

name: feature_03_jpg_to_pdf

jobs:
  ContinuousIntegration:
    name: Run Build, Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Build apps
        run: composer install

      - name: Launch Pint Linter
        run: vendor/bin/pint --preset psr12
