name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Run Dependencies & Linter
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: MySql in GitHub Actions
        uses: nnhy/mysql-action@v1.0

      # - name: Install Dependencies
      #   run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      # - name: Launch Linter
      #   run: ./vendor/bin/pint

      - name: Migrate Database
        run: php artisan migrate --force

      # - name: Launch Unit Test
      #   run: php artisan test
