name: feature_07_comment

on:
  push:
    branches:
      - feature_07_comment

jobs:
  ContinuousIntegration:
    name: Build Apps, Linter & Testing
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      # - name: Build Apps
      #   run: composer install

      # - name: Generate Storage
      #   run: php artisan storage:link

      # - name: Generate Environment
      #   run: cp .env.example .env.testing

      # - name: Generate Application Key
      #   run: |
      #     php artisan key:generate --env=testing
      #     sed -i 's/APP_ENV=local/APP_ENV=${{ secrets.APP_ENV }}/' .env.testing
      #     sed -i 's/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }} /' .env.testing
      #     sed -i 's/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }} /' .env.testing
      #     sed -i 's/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }} /' .env.testing
      #     sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }} /' .env.testing
      #     sed -i 's/<env name="DB_DATABASE" value="convert_testing"\/>/<env name="DB_DATABASE" value="${{ secrets.DB_DATABASE }}"\/>/' phpunit.xml

      # - name: Launch Linter
      #   run: |
      #     linter_output=$(./vendor/bin/pint)
      #     if [[ $linter_output == *"FIXED"* ]]; then
      #       echo "there is an error in your code format, correct it and push the code again!"
      #       exit 1
      #     fi

      # - name: Launch Unit Test
      #   run: ./vendor/bin/phpunit --testsuite Feature

      - name: Set CI status
        id: ci_status
        run: echo "success"

  ContinuousDeployment:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: ContinuousIntegration
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER_FTP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          args: --local-dir=./path/to/local/dir --remote-dir=/home/pwnhrmxj/save_ftp
