on:
  push:
    branches:
      - feature_02_png_tp_jpg

name: feature_02_png_tp_jpg

jobs:
  ContinuousIntegration:
    name: Run Build, Unit Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Build apps
        run: composer install

      - name: Run Unit Tests
        run: vendor/bin/phpunit

      - name: Launch Pint Linter
        run: vendor/bin/pint --preset psr12
